### PR TITLE
Replace x.getchildren with list(x) (Fix #281)

### LINKED ISSUE #281: Python 3.9 support
Trying to start the server on Python 3.9:

```
$ omero admin start
Traceback (most recent call last):
  File "/opt/anaconda3/envs/omeroweb/bin/omero", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/main.py", line 125, in main
    rv = omero.cli.argv()
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/cli.py", line 1784, in argv
    cli.invoke(args[1:])
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/cli.py", line 1222, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/cli.py", line 1299, in onecmd
    self.execute(line, previous_args)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/cli.py", line 1381, in execute
    args.func(args)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/prefs.py", line 79, in open_and_close_config
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/admin.py", line 832, in start
    self.startasync(args, config)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/prefs.py", line 79, in open_and_close_config
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/admin.py", line 784, in startasync
    self.rewrite(args, config)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/prefs.py", line 79, in open_and_close_config
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/admin.py", line 1161, in rewrite
    clear_tail(template_xml)
  File "/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/omero/plugins/admin.py", line 1158, in clear_tail
    for child in elem.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

Useful link for addressing that error:
https://stackoverflow.com/questions/10408927/how-to-get-all-sub-elements-of-an-element-tree-with-python-elementtree

Also failed to run integration tests on Python 3.9 recently.

### PR DESCRIPTION
**Pull request by joshmoore**
```
$ omero admin start
```
should now work on Python 3.9. See #281.

### CODE REVIEW

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/ is green
Proposing to push a 5.9.1 tag with the fix
